CREATE TABLE `plans` (
  `plan_id` varchar(48) NOT NULL,
  `title` varchar(254) NOT NULL,
  `title_internal` varchar(254) NOT NULL,
  `price` varchar(100) NOT NULL DEFAULT '0',
  `booking_type` varchar(24) NOT NULL DEFAULT 'direct',
  `category` varchar(254) DEFAULT NULL,
  `persons` int(11) NOT NULL DEFAULT 1,
  `adults` int(11) NOT NULL DEFAULT 0,
  `children` int(11) NOT NULL DEFAULT 0,
  `infants` int(11) NOT NULL DEFAULT 0,
  `small_description` mediumtext NOT NULL,
  `description` longtext NOT NULL,
  `date_range` varchar(254) NOT NULL,
  `start_date` varchar(100) NOT NULL,
  `end_date` varchar(100) NOT NULL,
  `min_days` int(11) NOT NULL DEFAULT 1,
  `max_days` int(11) NOT NULL DEFAULT 1,
  `cancelation_policy` longtext DEFAULT NULL,
  `available` tinyint(1) NOT NULL DEFAULT 1,
  `available_from_date` varchar(100) DEFAULT NULL,
  `available_until_date` varchar(100) DEFAULT NULL,
  `starting_type` varchar(48) NOT NULL,
  `adults_only` tinyint(1) NOT NULL DEFAULT 0,
  `family_friendly` tinyint(1) NOT NULL DEFAULT 1,
  `area_description` longtext DEFAULT NULL,
  `other_important_info` longtext DEFAULT NULL,
  `means_of_transport_arrival.type` varchar(20) NOT NULL,
  `means_of_transport_arrival.company_name` varchar(254) NOT NULL,
  `means_of_transport_arrival.start_time` varchar(100) NOT NULL,
  `means_of_transport_arrival.arrival_time` varchar(100) NOT NULL,
  `means_of_transport_arrival.number` varchar(254) NOT NULL,
  `means_of_transport_return.type` varchar(20) NOT NULL,
  `means_of_transport_return.company_name` varchar(254) NOT NULL,
  `means_of_transport_return.start_time` varchar(100) NOT NULL,
  `means_of_transport_return.arrival_time` varchar(100) NOT NULL,
  `means_of_transport_return.number` varchar(254) NOT NULL,
  `place_id` varchar(48) NOT NULL,
  `accommodation_id` varchar(48) NOT NULL,
  `discount.code_type` varchar(100) DEFAULT NULL,
  `discount.code_value` varchar(100) DEFAULT NULL,
  `discount.enabled` tinyint(1) NOT NULL DEFAULT 0,
  `discount.type` varchar(20) DEFAULT NULL,
  `discount.value` float DEFAULT NULL,
  PRIMARY KEY (`plan_id`),
  CONSTRAINT `plans_check` CHECK (`booking_type` in ('direct','request')),
  CONSTRAINT `plans_check_1` CHECK (`starting_type` in ('fixed_times','anytime_during_timerange')),
  CONSTRAINT `plans_check_3` CHECK ('means_of_transport_return.type' in ('airline','ship','train','bus')),
  CONSTRAINT `plans_check_4` CHECK ('discount.code_type' in ('discount','promotional','rate','convention_number','voucher')),
  CONSTRAINT `plans_check_5` CHECK ('discount.type' in ('percent','fixed'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci COMMENT='Thsi table saves the plans that the tourism office provides to its customers';