CREATE TABLE `secretariat` (
  `account_id` varchar(48) NOT NULL,
  `secretariat_id` varchar(48) NOT NULL,
  `first_name` varchar(254) NOT NULL,
  `last_name` varchar(254) NOT NULL,
  `email` varchar(254) NOT NULL,
  `phone` varchar(20) NOT NULL,
  `date_of_birth` date DEFAULT NULL,
  `id_number` varchar(100) DEFAULT NULL,
  `id_type` varchar(36) DEFAULT NULL,
  `place_of_residence.street` varchar(100) DEFAULT NULL,
  `place_of_residence.city` varchar(100) DEFAULT NULL,
  `place_of_residence.postal_code` varchar(100) DEFAULT NULL,
  `place_of_residence.state` varchar(100) DEFAULT NULL,
  `place_of_residence.country` varchar(100) DEFAULT NULL,
  `place_of_residence.longitude` float DEFAULT NULL,
  `place_of_residence.latitude` float DEFAULT NULL,
  `start_date` varchar(40) DEFAULT NULL,
  `still_working` tinyint(1) NOT NULL DEFAULT 1,
  `office_hours.start_time` varchar(40) DEFAULT NULL,
  `office_hours.end_time` varchar(40) DEFAULT NULL,
  `office_details.email` varchar(254) DEFAULT NULL,
  `office_details.phone` varchar(20) DEFAULT NULL,
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`secretariat_id`),
  KEY `secretariat_accounts_FK` (`account_id`),
  CONSTRAINT `secretariat_accounts_FK` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`account_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `secretariat_check` CHECK (`id_type` in ('id_card','passport'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci COMMENT='Here, saved the accounts that refers to a secretariat position into the office';